/auth/change-password endpoint implementation
bopvlk/tudor_match pull request #9
Opened 2024-01-14 11:11 UTC by maxpopovitch

2024-01-14 12:36 UTC, bopvlk requested changes

2024-01-14 12:36 UTC, bopvlk commented on pkg/controllers/users.go
> +	}
не варто стільки провірок робити, можна через || (or)  усі if з 181-199 рядок зробити.

2024-01-14 12:36 UTC, bopvlk commented on pkg/routers/routers.go
> +	api.POST("/auth/change-password", a.PasswordChange)
це треба у протектед поля таку можливіть давати тільки зареєстрованим користувачам

2024-01-14 12:36 UTC, bopvlk commented on pkg/services/users.go
> +}
Тут ти забув сам пароль змінити за допомогою метода UpdateUser там поставиш в entity.User два поля треба ID і новий пароль, id треба взяти з middleware (ще один момент чого протектед треба)

2024-01-14 20:44 UTC, maxpopovitch commented on pkg/controllers/users.go
> +	}
Не зрозумів тут, чесно кажучі. Я зробив різні перевірки, які перевіряють різні поля і повертають різні повідомлення. Що саме ти маєш на увазі?

2024-01-14 21:17 UTC, maxpopovitch commented on pkg/routers/routers.go
> +	api.POST("/auth/change-password", a.PasswordChange)
done

2024-01-14 21:21 UTC, maxpopovitch commented on pkg/services/users.go
> +}
implemented

2024-01-17 06:23 UTC, bopvlk approved these changes

2024-01-17 06:23 UTC, bopvlk commented on pkg/controllers/users.go
> +	}
я помилки конкретні то можна окрему функіцію написати, але думаю то поки що не на часі.

2024-01-17 14:21 UTC, merged